# Learning Objectives

- Understand how to create new variables in a DataFrame.
- Learn how to modify existing variables.

# Imports

```{python}
import pandas as pd

pd.options.mode.copy_on_write = True
```

```{python}
counties = pd.read_csv("data/us_counties_data.csv")
counties
```

```{python}
area_df = counties[["county","area_sq_miles","pop_20"]]
area_df
```
# Creating New Variables

```{python}
# New var with area in sq km
area_df["area_sq_km"] =area_df["area_sq_miles"]* 2.59
# New var with area in hectares
area_df["area_hectares"] = area_df["area_sq_km"] * 100
area_df
```

# Practice Q: Area in Acres

Using the area_df dataset, create a new column called area_acres by multiplying the area_sq_miles varaible by 640. Store the result back into area_df and display the DataFrame.

```{python}
area_df["area_acres"] = area_df["area_sq_miles"] * 640
area_df
```
# Modifying Existing Variables

```{python}
area_df["area_sq_km"].round(1)
area_df["area_sq_km"] = area_df["area_sq_km"].round(2)
area_df
```
Practice Q: Rounding 'area_acres'

Using the are_df dataset, round the area_acres variable to one decimal place. Update the DataFrame and display it.

```{python}
area_df["area_acres"] = area_df["area_acres"].round(1)
area_df
```
# Calculating with Multiple Variables

```{python}
area_df["pop_per_sq_km"] = (area_df["pop_20"] / area_df["area_sq_km"]).round(1)
area_df = area_df.sort_values(by= "pop_per_sq_km",ascending = False)
area_df
```

# Practice Q: Foreign Born Percentage

Use the counties dataset to calculate the percentage of foreign -born residents in each county. (Remember to multiply your proportion by 100). The variable foreign_born_num shows the number of foreign born residents and pop_so shows the total population. Which two counties have the highest percentage of foreign_born residents?

```{python}
counties
```


```{python}
counties ["foreign_born_residents"] = (counties["foreign_born_num"] / counties["pop_20"]) * 100
counties = counties.sort_values(by= "foreign_born_residents",ascending = False)
counties
```
Miami-Dade-FL and Queens, NY are the counties with the highest percentage of foreign born residents

# Creating Boolean Variables

```{python}
changes_df = counties[["county","pop_change_2010_2020","pct_emp_change_2010_2021"]]
changes_df
```

```{python}
changes_df["pop_change_2010_2020"]> 0
```

```{python}
changes_df["pop_increase"] = changes_df["pop_change_2010_2020"]> 0
changes_df["emp_increase"] = changes_df["pct_emp_change_2010_2021"]> 0
changes_df
```


```{python}
changes_df.query("pop_increase == True & emp_increase == False")
```

```{python}
changes_df.query("pop_increase & ~(emp_increase)")
```

```{python}
counties ["foreign_born_residents"] = (counties["foreign_born_num"] / counties["pop_20"]) * 100
counties ["foreign_born_pct_gt_30"] = counties["foreign_born_residents"] > 30
counties.query("foreign_born_pct_gt_30") == True
```
# Copy on Write Warning

```{python}
pd.options.mode.copy_on_write = True

counties_mini = counties[["county", "area_sq_miles"]]

counties_mini["area_sq_miles"] = counties_mini["area_sq_miles"].round(2)
counties_mini
```