---
title: "GAPMINDER | Global co2 Emissions and GDP Dashboard 2022"  
format: dashboard 
theme: cerulean

---
```{python}
import pandas as pd
import plotly.express as px
import itables
import numpy as np 

# Load co2 data
co2_df=pd.read_csv("project/co2_pcap_cons.csv")


# Load gdp data
gdp_df = pd.read_csv("project/gdp_pcap.csv")

# Load ISO data
iso_alpha = pd.read_csv("project/iso_alpha codes.csv")

co2_df_long = co2_df.melt(id_vars=['country'],var_name='year',value_name='co2_per_capita')
gdp_df_long = gdp_df.melt(id_vars=['country'],var_name='year',value_name='gdp')


# Drop missing Values View
co2_df_long = co2_df_long.dropna(subset=['co2_per_capita'])
gdp_df_long = gdp_df_long.dropna(subset=['gdp'])

# Convert gdp to numeric (ensures it's not string)
gdp_df_long['gdp'] = pd.to_numeric(gdp_df_long['gdp'], errors='coerce')

# Convert year to integer
co2_df_long['year'] = co2_df_long['year'].astype(int)
# Convert year to integer (optional but recommended)
gdp_df_long['year'] = gdp_df_long['year'].astype(int)

# Merging the two datasets
merged_df = pd.merge(co2_df_long,gdp_df_long,on=['country','year'])


# interpolating missing values
merged_df['gdp'] = merged_df['gdp'].interpolate(method='linear')
merged_df['co2_per_capita'] = merged_df['co2_per_capita'].interpolate(method='linear')

# round off gdp to 2 decimal places
merged_df['gdp'] = merged_df['gdp'].round(2)

# Use the most recent year
latest_year = merged_df['year'].max()
df_latest = merged_df[merged_df['year'] == latest_year]

merged_df['co2_per_capita'] = pd.to_numeric(merged_df['co2_per_capita'], errors='coerce')

df_latest['co2_per_capita'] = pd.to_numeric(df_latest['co2_per_capita'], errors='coerce')

# creating GDP category
bins =[300,2725,5150,7575,10000]
labels= ['Low' ,'Lower-Middle','Upper-Middle','High']

df_latest['gdp_category'] = pd.cut(df_latest['gdp'], bins=bins, labels=labels)

# Filter for the year 2022
merged_df_2022 = merged_df[merged_df['year'] == 2022]

merged_iso=df_latest.merge(iso_alpha,how ='left',on='country')

fig = px.scatter(
    df_latest,
    x='gdp',
    y='co2_per_capita',
    hover_name='country',
    title='CO₂ Emissions per Capita vs GDP per Capita_2022',
    labels={
        'gdp_per_capita': 'GDP per Capita (USD)',
        'co2_per_capita': 'CO₂ per Capita (metric tons)'
    },
    trendline='ols',  # Adds regression line
    log_x=True,       # Log scale for better visualization
    log_y=True,       # Optional log scale on Y-axis
    range_x=[300,10000],
    template='simple_white'
)
# Bar Chart - Top CO₂ Emitters
top10_co2 = merged_df_2022.sort_values(by='co2_per_capita',ascending=False).head (10)

bar_co2 = px.bar(top10_co2,
      x='co2_per_capita',
      y='country',
      color='co2_per_capita',
      title='Top 10 Countries by CO₂ per Capita_2022',
      color_continuous_scale="Blues"
    ).update_layout(showlegend=False,
    xaxis_title=None,coloraxis_showscale=False)  

 # Bar Chart - Top GDP countries
top10_gdp = merged_df_2022.sort_values(by='gdp',ascending=False).head (10)

bar_gdp = px.bar(top10_gdp,
      x='gdp',
      y='country',
      color='gdp',
      title='Top 10 Countries by GDP per Capita_2022',
    color_continuous_scale="Greens"
    ).update_layout(showlegend=False,

    xaxis_title=None,coloraxis_showscale=False)
correlation = df_latest[['gdp', 'co2_per_capita']].corr()

merged_iso=df_latest.merge(iso_alpha,how ='left',on='country')

 # Map: GDP per Capita by Country
fig5 = px.choropleth(merged_iso,
       locations='alpha-3',
       color='gdp_category',
       hover_name='country',
       title='World Map of GDP per Capita_2022',
    color_discrete_map= {'Low': '#90be6d', 'Lower-Middle': '#f9c74f', 'Upper-Middle':'#f3722c', 'High': '#f94144'}
).update_layout(showlegend=False,margin=dict(l=50, r=100, t=100, b=50),width=900,height=600     
)

  
fig11 = px.box(
    df_latest,
    x='gdp_category',
    y='co2_per_capita',
    color='gdp_category',
    title='Distribution of CO₂ Emissions by GDP Category'
).update_layout(showlegend=False)

# Convert to numeric (in case of object dtype)
merged_df['gdp'] = pd.to_numeric(merged_df['gdp'], errors='coerce')
merged_df['co2_per_capita'] = pd.to_numeric(merged_df['co2_per_capita'], errors='coerce')

# Filter for the year 2022
merged_df_2022 = merged_df[merged_df['year'] == 2022]



# Aggregate CO2 by GDP category
grouped = df_latest.groupby('gdp_category')['co2_per_capita'].sum().reset_index()

fig_bar = px.bar(
    grouped,
    x='gdp_category',
    y='co2_per_capita',
    title='Total CO₂ Emissions per Capita by GDP Category',
    labels={'gdp_category': 'GDP Category', 'co2_per_capita': 'Total CO₂ per Capita'},
    color='gdp_category'
)
   

# Calculate averages
avg_gdp_2022 = round(merged_df_2022['gdp'].mean(), 2)
avg_co2_2022 = round(merged_df_2022['co2_per_capita'].mean(), 2)
# Use string conversion when displaying
gdp_display = str(avg_gdp_2022)
co2_display = str(avg_co2_2022)

# Country with highest CO₂ per capita
highest_co2 = merged_df_2022.sort_values("co2_per_capita", ascending=False).head(1).squeeze()
highest_co2_country = highest_co2["country"]
highest_co2_value = round(highest_co2["co2_per_capita"], 1)

# Compute highest gdp
highest_row = merged_df_2022.sort_values("gdp", ascending=False).head(1).squeeze()
highest_gdp_country = highest_row["country"]
highest_gdp_value = round(highest_row["gdp"], 1)

# Notes : As gdp increases the co2 also increases_strong positive correlation. Top right: High GDP,High co2 emission per person
## Bottom right..high GDP,but low emissions per capita,top left: low gdp,high emissions,bottom left: low gdp,low emissions
## Generally, countries with higher GDP tend to emit more CO₂ per person. The positive slope indicates a strong economic activity link to emissions
```


```{python}
# Define thresholds
high_gdp_thresh = 7000
low_gdp_thresh = 3000
low_co2_thresh = 6.84
high_co2_thresh = 17.48

# Filter for High GDP, Low CO2
high_gdp_low_co2 = df_latest[
    (df_latest['gdp'] > high_gdp_thresh) &
    (df_latest['co2_per_capita'] < low_co2_thresh)
][['country', 'gdp', 'co2_per_capita']]

# Filter for Low GDP, High CO2
low_gdp_high_co2 = df_latest[
    (df_latest['gdp'] < low_gdp_thresh) &
    (df_latest['co2_per_capita'] > high_co2_thresh)
][['country', 'gdp', 'co2_per_capita']]

import plotly.graph_objects as go

import plotly.graph_objects as go

fig12 = go.Figure(data=[go.Table(
    header=dict(
        values=list(high_gdp_low_co2.columns),
        fill_color='skyblue',
        align='left',
        font=dict(color='black',size = 14)
    ),
    cells=dict(
        values=[high_gdp_low_co2[col] for col in high_gdp_low_co2.columns],
        fill_color='white',
        align='left',
        line_color='green',
        line_width=0.5,
        font=dict(color='black',size=12)
    )
)]).update_layout(
    title=dict(
        text='<b>High GDP, Low CO₂ Emission Countries</b>',
        font=dict(size=18)
    ),
    height=600
)
```


# INTRODUCTION

**Data Origin and Description**


*This data comes from the python `plotly.express` library’s `gapminder` dataset, which is originally sourced from the Gapminder Foundation.*

*The Gapminder Foundation is a non-profit venture that promotes sustainable global development and achievement of the United Nations Millennium Development Goals by increasing use and understanding of statistics and other information about social, economic, and environmental development.*


**Dashboard Overview: co2 Emissions and GDP per Capita_2022**


*This dashboard provides a visual exploration of the relationship between a country's economic output (measured by GDP per capita) and its environmental impact (measured by CO₂ emissions per capita). Using data from Gapminder and other global datasets, the dashboard allows users to:*

-Compare countries based on their GDP and CO₂ emissions.

-Track trends over time (1990–2022) to observe how economic growth influences emissions.

-Group countries by income levels to assess differences across Low, Medium, and High GDP categories.

-Explore interactive visualizations such as scatter plots, choropleth maps, bar charts, and time series lines.

-Identify outliers or key contributors, such as countries with high GDP but relatively low emissions, or vice versa.




# HOME

## Row 1 {height=30%}

::: {.valuebox icon="globe" color="#1E90FF" title="Average GDP per Capita (USD)"}

`{python} gdp_display`

:::

::: {.valuebox icon="cloud" color="#00BFFF" title="Average co2 per Capita (metric tons)"}

`{python} co2_display`


:::

::: {.valuebox icon="globe" color="#1E90FF" title="Country_Highest GDP"}

`{python} str(highest_gdp_value)`

`{python} highest_gdp_country`

:::

::: {.valuebox icon="cloud" color="#00BFFF" title="Country_Highest CO2"}

`{python} str(highest_co2_value)`

`{python} highest_co2_country`

:::

## Row 2 {height=70%}

### {width=50%}

```{python}
bar_co2
```

### {width=50%}

```{python}
bar_gdp
```

# GLOBAL

## Row 1 {height=70%}

```{python}
fig5

```

## Row 1 {height=30%}

The map categorizes countries into four GDP per capita groups — 
<span style="color:#90be6d; font-weight:bold">Low (Green)</span>, 
<span style="color:#f9c74f; font-weight:bold">Lower-Middle (Yellow)</span>, 
<span style="color:#f3722c; font-weight:bold">Upper-Middle (Orange)</span>, and 
<span style="color:#f94144; font-weight:bold">High (Red)</span> — offering a clear visual of global economic disparities.


# CORRELATION

## Row 1 {height=70%}

```{python}
fig

```

## Row 2 {height=30%}

### Column {width="80%"}

**The scatter plot illustrates the relationship between CO2 emissions per capita and GDP per capita across countries. The Ordinary Least Squares (OLS) line shows a strong, positive linear trend, indicating that higher GDP per capita is associated with higher CO2 emissions per capita. In essence, wealthier countries tend to have a larger carbon footprint, as represented by the nearly straight, upward-sloping OLS line.**

# TABLE

### Column {width="50%"}

## High GDP and Low co2 Countries

```{python}
fig12
```

**Countries with high GDP and low CO₂ emissions per capita demonstrate that strong economic performance can be achieved alongside environmental sustainability. These nations often invest in clean energy, enforce environmental regulations, and maintain energy-efficient systems. Their economies are typically service- or technology-driven, producing less carbon compared to industrial-heavy economies. As a result, they serve as key examples of how economic growth does not have to come at the expense of the environment.**

# GRAPH

## Row 2 {height=60%}

```{python}
fig11
```

## Row 2 {height=40%}

**CO₂ Emissions by GDP Category**

The box plot illustrates notable differences in CO₂ emissions per capita across income groups. Countries with Low GDP have the lowest median emissions at 0.46 metric tons, reflecting limited industrialization. Lower-Middle GDP countries show the highest median emissions at 3.77, possibly due to increasing energy use with fewer emission controls. Interestingly, Upper-Middle GDP countries have a slightly lower median of 2.79, and High GDP countries report a median of 3.22, which may indicate more efficient technologies and stricter environmental regulations in wealthier nations.

# DATA

```{python}
# Display full dataset with itables
itables.show(merged_df_2022, caption="Gapminder Dataset_GDP Per Capita and co2 Emissions (2022)", buttons=["csvHtml5"])
```